import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./components/navbar/navbar";
const inter = Inter({ subsets: ["latin"] });
import { UserProvider } from "@auth0/nextjs-auth0/client";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={`bg-light-subtle${inter.className}`}>
          <Navbar />
          <div className=" max-w-screen-xl  mx-auto ">{children}</div>
        </body>
      </UserProvider>
    </html>
  );
}
